[build]
  base = "docs/"
  publish = "src/.vuepress/dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "https://docs--bibleup.netlify.app/*"
  to = "https://bibleup.netlify.app/docs/:splat"
  status = 301
  force = true
